---
# tasks file for devbox

  - name: Install Ubuntu PHP Development headers/libraries
    apt: name=php5-dev state=installed
    when: is_ubuntu

  - name: Install CentOS PHP Development Libraries
    yum: name=php55w-devel state=installed
    when: is_centos

  - name: Install make
    action: "{{ ansible_pkg_mgr }} name=make state=installed"

  - name: Install xdebug
    shell: pecl upgrade xdebug

  - name: Configure xdebug
    template:
      src=xdebug.ini.j2
      dest=/etc/php5/mods-available/xdebug.ini
      owner=root group=root mode=0644
    when: is_ubuntu

  - name: Configure PHP development
    template:
      src=dev.ini.j2
      dest=/etc/php5/mods-available/dev.ini
      owner=root group=root mode=0644
    when: is_ubuntu

  - name: Activate WK dev
    shell: php5enmod {{ item }}
    with_items:
      - xdebug
      - dev
    when: is_ubuntu
